name: Build
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: run build
        run: ./script/build-xcframework.sh 1.11.1 OpenSSL_1_1_1w
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: CSSH.xcframework
          path: /Users/runner/work/CSSH/CSSH/build/CSSH.xcframework
